export const wallpapers = [
  {
    id: 1,
    url: "https://i.imgur.com/onVtToF.png",
    larger: "https://i.imgur.com/onVtToFh.png",
    resolution: "1920 x 1080 px",
    size: "779 KB",
  },
  {
    id: 2,
    url: "https://i.imgur.com/06a0v7O.png",
    larger: "https://i.imgur.com/06a0v7Oh.png",
    resolution: "1920 x 1080 px",
    size: "1.48 MB",
  },
  {
    id: 3,
    url: "https://i.imgur.com/wXMTixZ.png",
    larger: "https://i.imgur.com/wXMTixZh.png",
    resolution: "2560 x 1440 px",
    size: "2.38 MB",
  },
  {
    id: 4,
    url: "https://i.imgur.com/XAuGL0u.png",
    larger: "https://i.imgur.com/XAuGL0uh.png",
    resolution: "2560 x 1440 px",
    size: "2.24 MB",
  },
  {
    id: 5,
    url: "https://i.imgur.com/8cbBN0M.png",
    larger: "https://i.imgur.com/8cbBN0Mh.png",
    resolution: "2560 x 1440 px",
    size: "2.36 MB",
  },
  {
    id: 6,
    url: "https://i.imgur.com/AqA8s39.png",
    larger: "https://i.imgur.com/AqA8s39h.png",
    resolution: "2560 x 1440 px",
    size: "1.80 MB",
  },
  {
    id: 7,
    url: "https://i.imgur.com/QqgZ8zZ.png",
    larger: "https://i.imgur.com/QqgZ8zZh.png",
    resolution: "1920 x 1080 px",
    size: "2.85 MB",
  },
  {
    id: 8,
    url: "https://i.imgur.com/DnBvIzz.png",
    larger: "https://i.imgur.com/DnBvIzzh.png",
    resolution: "1920 x 1080 px",
    size: "1.46 MB",
  },
];
