export const photography = [
  {
    id: 1,
    url: "https://i.imgur.com/vt9d2Pb.jpg",
    date: "08-Nov-2018",
    description: "Vintage bicycle of a friend",
  },
  {
    id: 2,
    url: "https://i.imgur.com/96hZIA4.jpg",
    date: "09-Nov-2018",
    description: "Just a plant",
  },
  {
    id: 3,
    url: "https://i.imgur.com/psxsrL4.jpg",
    date: "11-Nov-2018",
    description: "Interesting house close to where I live",
  },
  {
    id: 4,
    url: "https://i.imgur.com/uXCEr97.jpg",
    date: "12-Nov-2018",
    description: "Break time at work",
  },
  {
    id: 5,
    url: "https://i.imgur.com/Z9rv86a.jpg",
    date: "06-Nov-2018",
    description: "Little plant was blooming ",
  },
  {
    id: 6,
    url: "https://i.imgur.com/rtvIKOC.jpg",
    date: "03-Jan-2019",
    description: "Brother rabbits",
  },
  {
    id: 7,
    url: "https://i.imgur.com/lcP3dqM.jpg",
    date: "05-Dic-2018",
    description: "No construir",
  },
  {
    id: 8,
    url: "https://i.imgur.com/EsJYNDp.jpg",
    date: "04-Dic-2018",
    description: "Bicycle in the park",
  },
  {
    id: 9,
    url: "https://i.imgur.com/e6gRf2P.jpg",
    date: "06-Dic-2018",
    description: "Quiosco",
  },
  {
    id: 10,
    url: "https://i.imgur.com/avYk7tu.jpg",
    date: "09-Dic-2018",
    description: "Water fountain, no water",
  },
  {
    id: 11,
    url: "https://i.imgur.com/y3Cjeoj.jpg",
    date: "03-Feb-2019",
    description: "Flying",
  },
  {
    id: 12,
    url: "https://i.imgur.com/Bb7GBYV.jpg",
    date: "30-Nov-2018",
    description: "Bicycle, bicycle, bicycle, bicycle",
  },
  {
    id: 13,
    url: "https://i.imgur.com/qG3BiyQ.jpg",
    date: "13-Jan-2019",
    description: "Old train station",
  },
  {
    id: 14,
    url: "https://i.imgur.com/xC7oJOv.jpg",
    date: "27-Nov-2018",
    description: "LA ESTRELLA",
  },
  {
    id: 15,
    url: "https://i.imgur.com/WRzgSXi.jpg",
    date: "19-Mar-2019",
    description: "Dream car",
  },
  {
    id: 16,
    url: "https://i.imgur.com/2LxcEHy.jpg",
    date: "10-Mar-2019",
    description: "Beetle",
  },
  {
    id: 17,
    url: "https://i.imgur.com/7sXF1C0.jpg",
    date: "10-Dic-2018",
    description: "Factory",
  },

  {
    id: 18,
    url: "https://i.imgur.com/vjtbNfr.jpg",
    date: "17-Mar-2019",
    description: "Last light",
  },
  {
    id: 19,
    url: "https://i.imgur.com/c1lneRN.jpg",
    date: "19-Mar-2019",
    description: "Beauty flowers",
  },
  {
    id: 20,
    url: "https://i.imgur.com/WNs6NgF.jpg",
    date: "10-Mar-2019",
    description: "Vocho",
  },
  {
    id: 20,
    url: "https://i.imgur.com/SDT5nAb.jpg",
    date: "01-Feb-2019",
    description: "Before the flight",
  },
];
