export const weeks = [
  {
    number: 1,
    title: "the really true beginning",
    posts: [
      {
        title: "🐰🐰",
        date: "28-Jun-2021",
        url: "https://i.imgur.com/4i40dAs.jpg",
        large: "https://i.imgur.com/4i40dAsl.jpg",
        behind: "https://i.imgur.com/a6FUhdVh.jpg",
        resolution: "2400 x 3000",
        size: "11.1",
      },
      {
        title: "THE QUESTION",
        date: "29-Jun-2021",
        url: "https://i.imgur.com/hj9ng5K.jpg",
        large: "https://i.imgur.com/hj9ng5Kl.jpg",
        behind: "https://i.imgur.com/LGdXLKxh.jpg",
        resolution: "2400 x 3000",
        size: "10.9",
      },
      {
        title: "SHIP",
        date: "30-Jun-2021",
        url: "https://i.imgur.com/tk7OMKR.jpg",
        large: "https://i.imgur.com/tk7OMKRl.jpg",
        behind: "https://i.imgur.com/mieAvlLh.jpg",
        resolution: "2400 x 3000",
        size: "12.1",
      },
      {
        title: "LOST",
        date: "01-Jul-2021",
        url: "https://i.imgur.com/JcshEjX.jpg",
        large: "https://i.imgur.com/JcshEjXl.jpg",
        behind: "https://i.imgur.com/n4tmFUJh.jpg",
        resolution: "2400 x 3000",
        size: "12.8",
      },
      {
        title: "🥶🥶🥶",
        date: "02-Jul-2021",
        url: "https://i.imgur.com/SnpboS2.jpg",
        large: "https://i.imgur.com/SnpboS2l.jpg",
        behind: "https://i.imgur.com/tFhAP59h.jpg",
        resolution: "2400 x 3000",
        size: "14.4",
      },
    ],
  },
  {
    number: 2,
    title: "",
    posts: [
      {
        title: "PRISMA FULL",
        date: "05-Jul-2021",
        url: "https://i.imgur.com/ssrquCb.jpg",
        large: "https://i.imgur.com/ssrquCbl.jpg",
        behind: "https://i.imgur.com/MrGMOGsh.jpg",
        resolution: "2400 x 3000",
        size: "13.9",
      },
      {
        title: "Thank you for your purchase! 🤝🏻",
        date: "06-Jul-2021",
        url: "https://i.imgur.com/9Look2H.jpg",
        large: "https://i.imgur.com/9Look2Hl.jpg",
        behind: "https://i.imgur.com/9cPqF3zh.jpg",
        resolution: "2400 x 3000",
        size: "13.8",
      },
      {
        title: "SH*T HAPPENS 💩",
        date: "07-Jul-2021",
        url: "https://i.imgur.com/7Eufx4L.jpg",
        large: "https://i.imgur.com/7Eufx4Ll.jpg",
        behind: "https://i.imgur.com/xOL77ayh.jpg",
        resolution: "2400 x 3000",
        size: "13.0",
      },

      {
        title: "SUS",
        date: "08-Jul-2021",
        url: "https://i.imgur.com/wIFUEVe.jpg",
        large: "https://i.imgur.com/wIFUEVel.jpg",
        behind: "https://i.imgur.com/xnaAj7Eh.jpg",
        resolution: "2400 x 3000",
        size: "16.7",
      },
      {
        title: "BANANAFETT",
        date: "09-Jul-2021",
        url: "https://i.imgur.com/aJO467M.jpg",
        large: "https://i.imgur.com/aJO467Ml.jpg",
        behind: "https://i.imgur.com/zglV62sh.png",
        resolution: "2400 x 3000",
        size: "15.2",
      },
    ],
  },
  {
    number: 3,
    title: "",
    posts: [
      {
        title: "SWEET DEAD",
        date: "12-Jul-2021",
        url: "https://i.imgur.com/CnbCPle.jpg",
        large: "https://i.imgur.com/CnbCPlel.jpg",
        behind: "https://i.imgur.com/14wvO4bh.jpg",
        resolution: "2400 x 3000",
        size: "13.0",
      },
      {
        title: "🌞",
        date: "13-Jul-2021",
        url: "https://i.imgur.com/ClWROSw.jpg",
        large: "https://i.imgur.com/ClWROSwl.jpg",
        behind: "https://i.imgur.com/c0lLdUbh.jpg",
        resolution: "2400 x 3000",
        size: "13.8",
      },
      {
        title: "CALM WATERS",
        date: "14-Jul-2021",
        url: "https://i.imgur.com/JKI7viH.jpg",
        large: "https://i.imgur.com/JKI7viHl.jpg",
        behind: "https://i.imgur.com/JstynZhh.jpg",
        resolution: "2400 x 3000",
        size: "17.8",
      },
      {
        title: "FRENCH BURGER 🍔🍟",
        date: "15-Jul-2021",
        url: "https://i.imgur.com/eLohRJV.jpg",
        large: "https://i.imgur.com/eLohRJVl.jpg",
        behind: "https://i.imgur.com/yXEYfWEh.jpg",
        resolution: "2400 x 3000",
        size: "15.4",
      },
      {
        title: "ROLL",
        date: "16-Jul-2021",
        url: "https://i.imgur.com/MD3RDIK.jpg",
        large: "https://i.imgur.com/MD3RDIKl.jpg",
        behind: "https://i.imgur.com/CWhhO5wh.jpg",
        resolution: "2400 x 3000",
        size: "16.4",
      },
    ],
  },
  {
    number: 4,
    title: "",
    posts: [
      {
        title: "VERY NEW SOUNDMOJIS (AND GOATMOJIS! 🐐)",
        date: "19-Jul-2021",
        url: "https://i.imgur.com/UmW9Z16.jpg",
        large: "https://i.imgur.com/UmW9Z16l.jpg",
        behind: "https://i.imgur.com/H7qvJ8Fh.jpg",
        resolution: "2400 x 3000",
        size: "14.7",
      },
      {
        title: "FINDING SIGNALS",
        date: "20-Jul-2021",
        url: "https://i.imgur.com/TEk1URQ.jpg",
        large: "https://i.imgur.com/TEk1URQl.jpg",
        behind: "https://i.imgur.com/tUdLspdh.jpg",
        resolution: "2400 x 3000",
        size: "16.1",
      },
      {
        title: "KICK IT UP",
        date: "21-Jul-2021",
        url: "https://i.imgur.com/JbfA40d.jpg",
        large: "https://i.imgur.com/JbfA40dl.jpg",
        behind: "https://i.imgur.com/Ln0R8vQh.jpg",
        resolution: "2400 x 3000",
        size: "16.8",
      },
      {
        title: "URBAN",
        date: "22-Jul-2021",
        url: "https://i.imgur.com/ppMBB0J.jpg",
        large: "https://i.imgur.com/ppMBB0Jl.jpg",
        behind: "https://i.imgur.com/ppSaAl9h.jpg",
        resolution: "2400 x 3000",
        size: "14.7",
      },
      {
        title: "DAY OFF",
        date: "23-Jul-2021",
        url: "https://i.imgur.com/0jsGRAA.jpg",
        large: "https://i.imgur.com/0jsGRAAl.jpg",
        behind: "https://i.imgur.com/o7Zsl9fh.jpg",
        resolution: "2400 x 3000",
        size: "13.2",
      },
    ],
  },
  {
    number: 5,
    title: "",
    posts: [
      {
        title: "LAST MISSION",
        date: "26-Jul-2021",
        url: "https://i.imgur.com/lHq86DV.jpg",
        large: "https://i.imgur.com/lHq86DVl.jpg",
        behind: "https://i.imgur.com/4wiKL9yh.jpg",
        resolution: "2400 x 3000",
        size: "16.8",
      },
      {
        title: "ABDUZCAN",
        date: "27-Jul-2021",
        url: "https://i.imgur.com/Ks1nHma.jpg",
        large: "https://i.imgur.com/Ks1nHmal.jpg",
        behind: "https://i.imgur.com/5t8ckHQh.png",
        resolution: "2400 x 3000",
        size: "12.6",
      },
      {
        title: "LIFE GOES ON...",
        date: "28-Jul-2021",
        url: "https://i.imgur.com/OqRUcbX.jpg",
        large: "https://i.imgur.com/OqRUcbXl.jpg",
        behind: "https://i.imgur.com/KjT9Mozh.png",
        resolution: "2400 x 3000",
        size: "13.5",
      },
      {
        title: "INACCESIBLE",
        date: "29-Jul-2021",
        url: "https://i.imgur.com/1ehuKXQ.jpg",
        large: "https://i.imgur.com/1ehuKXQl.jpg",
        behind: "https://i.imgur.com/lZ7UJU5h.png",
        resolution: "2400 x 3000",
        size: "17.1",
      },
      {
        title: "LET IT GO",
        date: "30-Jul-2021",
        url: "https://i.imgur.com/NAC9Lsg.jpg",
        large: "https://i.imgur.com/NAC9Lsgl.jpg",
        behind: "https://i.imgur.com/NHQXLWWh.png",
        resolution: "2400 x 3000",
        size: "16.8",
      },
    ],
  },
  {
    number: 6,
    title: "",
    posts: [
      {
        title: "FORSAKEN",
        date: "02-Aug-2021",
        url: "https://i.imgur.com/F5BlldW.jpg",
        large: "https://i.imgur.com/F5BlldWl.jpg",
        behind: "https://i.imgur.com/OSUd0F7h.png",
        resolution: "2400 x 3000",
        size: "16.8",
      },
      {
        title: "BREAKAGE",
        date: "03-Aug-2021",
        url: "https://i.imgur.com/aoT5mRZ.jpg",
        large: "https://i.imgur.com/aoT5mRZl.jpg",
        behind: "https://i.imgur.com/2RUKuC1h.png",
        resolution: "2400 x 3000",
        size: "15.1",
      },
      {
        title: "REDECORATE",
        date: "04-Aug-2021",
        url: "https://i.imgur.com/tcXRomd.jpg",
        large: "https://i.imgur.com/tcXRomdl.jpg",
        behind: "https://i.imgur.com/IgYam0Dh.png",
        resolution: "2400 x 3000",
        size: "13.5",
      },
      {
        title: "REPLACING",
        date: "05-Aug-2021",
        url: "https://i.imgur.com/B2SSYJI.jpg",
        large: "https://i.imgur.com/B2SSYJIl.jpg",
        behind: "https://i.imgur.com/BdVzgrZh.png",
        resolution: "2400 x 3000",
        size: "13.2",
      },
      {
        title: "IN A VOYAGE",
        date: "06-Aug-2021",
        url: "https://i.imgur.com/QTZp7d9.jpg",
        large: "https://i.imgur.com/QTZp7d9l.jpg",
        behind: "https://i.imgur.com/X7L8wbAh.png",
        resolution: "2400 x 3000",
        size: "14.1",
      },
    ],
  },
  {
    number: 7,
    title: "",
    posts: [
      {
        title: "AXOLOTL'S LUNCH",
        date: "09-Aug-2021",
        url: "https://i.imgur.com/OsMm0a1.jpg",
        large: "https://i.imgur.com/OsMm0a1l.jpg",
        behind: "https://i.imgur.com/RazMq4fh.png",
        resolution: "2400 x 3000",
        size: "14.6",
      },
      {
        title: "PICKING FLOWERS",
        date: "10-Aug-2021",
        url: "https://i.imgur.com/62CHe8x.png",
        large: "https://i.imgur.com/62CHe8xl.png",
        behind: "https://i.imgur.com/xyviUF7h.png",
        resolution: "2400 x 3000",
        size: "4.0",
      },
      {
        title: "METARABBITMASK",
        date: "11-Aug-2021",
        url: "https://i.imgur.com/L5qKFWe.png",
        large: "https://i.imgur.com/L5qKFWel.png",
        behind: "https://i.imgur.com/sOuakYNh.png",
        resolution: "2400 x 3000",
        size: "4.51",
      },
      {
        title: "DEEP",
        date: "12-Aug-2021",
        url: "https://i.imgur.com/UUtmCoP.png",
        large: "https://i.imgur.com/UUtmCoPl.png",
        behind: "https://i.imgur.com/1eXxUfKh.png",
        resolution: "2400 x 3000",
        size: "4.54",
      },
      {
        title: "CONTAINER",
        date: "13-Aug-2021",
        url: "https://i.imgur.com/iEvOuH9.png",
        large: "https://i.imgur.com/iEvOuH9l.png",
        behind: "https://i.imgur.com/QvM89MPh.png",
        resolution: "2400 x 3000",
        size: "3.65",
      },
    ],
  },
  {
    number: 8,
    title: "",
    posts: [
      {
        title: "BLAST",
        date: "16-Aug-2021",
        url: "https://i.imgur.com/G3mVtcz.png",
        large: "https://i.imgur.com/G3mVtczl.png",
        behind: "https://i.imgur.com/K5tMy17h.png",
        resolution: "2400 x 3000",
        size: "2.69",
      },
      {
        title: "ARCADE",
        date: "17-Aug-2021",
        url: "https://i.imgur.com/5w2SKkO.png",
        large: "https://i.imgur.com/5w2SKkOl.png",
        behind: "https://i.imgur.com/OCuEioMh.png",
        resolution: "2400 x 3000",
        size: "3.13",
      },
      {
        title: "WHEN PIGS FLY",
        date: "18-Aug-2021",
        url: "https://i.imgur.com/tcKWtFe.png",
        large: "https://i.imgur.com/tcKWtFel.png",
        behind: "https://i.imgur.com/41CHslWh.png",
        resolution: "2400 x 3000",
        size: "4.16",
      },
      {
        title: "GAME BOT",
        date: "19-Aug-2021",
        url: "https://i.imgur.com/rbAEsuo.png",
        large: "https://i.imgur.com/rbAEsuol.png",
        behind: "https://i.imgur.com/vxXyytXh.png",
        resolution: "2400 x 3000",
        size: "4.13",
      },
      {
        title: "LOCKED",
        date: "20-Aug-2021",
        url: "https://i.imgur.com/lbPiJdM.png",
        large: "https://i.imgur.com/lbPiJdMl.png",
        behind: "https://i.imgur.com/rkJuJeZh.png",
        resolution: "2400 x 3000",
        size: "3.67",
      },
    ],
  },
  {
    number: 9,
    title: "",
    posts: [
      {
        title: "FROG DOMINATION 🐸",
        date: "23-Aug-2021",
        url: "https://i.imgur.com/KKh5lRv.png",
        large: "https://i.imgur.com/KKh5lRvl.png",
        behind: "https://i.imgur.com/Nb3Xmwrh.png",
        resolution: "2400 x 3000",
        size: "3.94",
      },
      {
        title: "HEAVY MACHINE GUN!",
        date: "24-Aug-2021",
        url: "https://i.imgur.com/EkNmLIb.png",
        large: "https://i.imgur.com/EkNmLIbl.png",
        behind: "https://i.imgur.com/wCMXm5Dh.png",
        resolution: "2400 x 3000",
        size: "4.0",
      },
      {
        title: "ENCAPSULATED",
        date: "25-Aug-2021",
        url: "https://i.imgur.com/hfzqbUs.png",
        large: "https://i.imgur.com/hfzqbUsl.png",
        behind: "https://i.imgur.com/wG4ODFOh.png",
        resolution: "2400 x 3000",
        size: "3.70",
      },
      {
        title: "IMMUNITY",
        date: "26-Aug-2021",
        url: "https://i.imgur.com/w8z2oVk.png",
        large: "https://i.imgur.com/w8z2oVkl.png",
        behind: "https://i.imgur.com/NVLL3bvh.png",
        resolution: "2400 x 3000",
        size: "4.80",
      },
      {
        title: "VUELO",
        date: "27-Aug-2021",
        url: "https://i.imgur.com/PHAhskT.png",
        large: "https://i.imgur.com/PHAhskTl.png",
        behind: "https://i.imgur.com/bdlNLSsh.png",
        resolution: "2400 x 3000",
        size: "3.75",
      },
    ],
  },
  {
    number: 10,
    title: "",
    posts: [
      {
        title: "ROTTEN EGG 🥚",
        date: "30-Aug-2021",
        url: "https://i.imgur.com/AMQjgHY.png",
        large: "https://i.imgur.com/AMQjgHYl.png",
        behind: "https://i.imgur.com/nn8Tvxzh.png",
        resolution: "2400 x 3000",
        size: "4.17",
      },
      {
        title: "Flows",
        date: "31-Aug-2021",
        url: "https://i.imgur.com/0IU8JVq.png",
        large: "https://i.imgur.com/0IU8JVql.png",
        behind: "https://i.imgur.com/OW71fRnh.png",
        resolution: "2400 x 3000",
        size: "4.40",
      },
      {
        title: "⚛️.jsx",
        date: "01-Sep-2021",
        url: "https://i.imgur.com/td7mhcL.png",
        large: "https://i.imgur.com/td7mhcLl.png",
        behind: "https://i.imgur.com/pxGxk5Lh.png",
        resolution: "2400 x 3000",
        size: "3.53",
      },
      {
        title: "FULL MAIL",
        date: "02-Sep-2021",
        url: "https://i.imgur.com/4VLwWfH.png",
        large: "https://i.imgur.com/4VLwWfHl.png",
        behind: "https://i.imgur.com/cZMnW0ih.png",

        resolution: "2400 x 3000",
        size: "3.15",
      },
      {
        title: "HULL",
        date: "03-Sep-2021",
        url: "https://i.imgur.com/hMQ5qR3.png",
        large: "https://i.imgur.com/hMQ5qR3l.png",
        behind: "https://i.imgur.com/7Oxz7VKh.png",
        resolution: "2400 x 3000",
        size: "4.59",
      },
    ],
  },
  {
    number: 11,
    title: "",
    posts: [
      {
        title: "SUPER WAY",
        date: "06-Sep-2021",
        url: "https://i.imgur.com/Pbde3Iy.png",
        large: "https://i.imgur.com/Pbde3Iyl.png",
        behind: "https://i.imgur.com/1sSxccPh.png",
        resolution: "2400 x 3000",
        size: "3.51",
      },
      {
        title: "SAMURAI 👹",
        date: "07-Sep-2021",
        url: "https://i.imgur.com/cYk3lf3.png",
        large: "https://i.imgur.com/cYk3lf3l.png",
        behind: "https://i.imgur.com/3UGDPZth.png",
        resolution: "2400 x 3000",
        size: "4.58",
      },
      {
        title: "POKE BORN",
        date: "08-Sep-2021",
        url: "https://i.imgur.com/NiqHkNJ.png",
        large: "https://i.imgur.com/NiqHkNJl.png",
        behind: "https://i.imgur.com/WrjxMmZh.png",
        resolution: "2400 x 3000",
        size: "4.39",
      },
      {
        title: "RADIANCE",
        date: "09-Sep-2021",
        url: "https://i.imgur.com/ZpSYyaf.png",
        large: "https://i.imgur.com/ZpSYyafl.png",
        behind: "https://i.imgur.com/0G8tAEhh.png",
        resolution: "2400 x 3000",
        size: "4.93",
      },
      {
        title: "NOT FRIENDLY",
        date: "10-Sep-2021",
        url: "https://i.imgur.com/R6Ky5K2.png",
        large: "https://i.imgur.com/R6Ky5K2l.png",
        behind: "https://i.imgur.com/oHAXgtPh.png",
        resolution: "2400 x 3000",
        size: "4.69",
      },
    ],
  },
  {
    number: 12,
    title: "",
    posts: [
      {
        title: "COME BACK",
        date: "13-Sep-2021",
        url: "https://i.imgur.com/oUVAJiN.png",
        large: "https://i.imgur.com/oUVAJiNl.png",
        behind: "https://i.imgur.com/CWfj1Vth.png",
        resolution: "2400 x 3000",
        size: "4.73",
      },
      {
        title: "ASSEMBLY",
        date: "14-Sep-2021",
        url: "https://i.imgur.com/I2gdIRb.png",
        large: "https://i.imgur.com/I2gdIRbl.png",
        behind: "https://i.imgur.com/wjo33wah.png",
        resolution: "2400 x 3000",
        size: "4.74",
      },
      {
        title: "PATRIA 🇲🇽",
        date: "15-Sep-2021",
        url: "https://i.imgur.com/ebFkSEm.png",
        large: "https://i.imgur.com/ebFkSEml.png",
        behind: "https://i.imgur.com/6XV1NIdh.png",
        resolution: "2400 x 3000",
        size: "3.29",
      },
      {
        title: "CONNECTED",
        date: "16-Sep-2021",
        url: "https://i.imgur.com/0U5wHfb.png",
        large: "https://i.imgur.com/0U5wHfbl.png",
        behind: "https://i.imgur.com/3wwTvcVh.png",
        resolution: "2400 x 3000",
        size: "4.76",
      },
      {
        title: "PIPEDREAM",
        date: "17-Sep-2021",
        url: "https://i.imgur.com/l5I1tT2.png",
        large: "https://i.imgur.com/l5I1tT2l.png",
        behind: "https://i.imgur.com/DaubYssh.png",
        resolution: "2400 x 3000",
        size: "3.86",
      },
    ],
  },
  {
    number: 13,
    title: "",
    posts: [
      {
        title: "SOLIDARITY",
        date: "20-Sep-2021",
        url: "https://i.imgur.com/1CwV6iq.jpg",
        large: "https://i.imgur.com/1CwV6iql.jpg",
        behind: "https://i.imgur.com/uC0wS6Xh.png",
        resolution: "2400 x 3000",
        size: "5.68",
      },
      {
        title: "TAKE THE CONTROL",
        date: "21-Sep-2021",
        url: "https://i.imgur.com/rOxY8zF.png",
        large: "https://i.imgur.com/rOxY8zFl.png",
        behind: "https://i.imgur.com/Uo6LvgIh.png",
        resolution: "2400 x 3000",
        size: "4.66",
      },
      {
        title: "WATCHING",
        date: "22-Sep-2021",
        url: "https://i.imgur.com/wAoBqFV.png",
        large: "https://i.imgur.com/wAoBqFVl.png",
        behind: "https://i.imgur.com/8zoS61wh.png",
        resolution: "2400 x 3000",
        size: "4.99",
      },
      {
        title: "BANANART",
        date: "23-Sep-2021",
        url: "https://i.imgur.com/JJ2P4PR.jpg",
        large: "https://i.imgur.com/JJ2P4PRl.jpg",
        behind: "https://i.imgur.com/79fOlMwh.png",
        resolution: "2400 x 3000",
        size: "5.27",
      },
      {
        title: "GAME",
        date: "24-Sep-2021",
        url: "https://i.imgur.com/2abfb8n.png",
        large: "https://i.imgur.com/2abfb8nl.png",
        behind: "https://i.imgur.com/n9cM5NBh.png",
        resolution: "2400 x 3000",
        size: "4.41",
      },
    ],
  },
  {
    number: 14,
    title: "",
    posts: [
      {
        title: "KRAKEN GAME",
        date: "27-Sep-2021",
        url: "https://i.imgur.com/vx6vIYO.png",
        large: "https://i.imgur.com/vx6vIYOl.png",
        behind: "https://i.imgur.com/mhkyziKh.png",
        resolution: "2400 x 3000",
        size: "4.48",
      },
      {
        title: "SPHERE RAY",
        date: "28-Sep-2021",
        url: "https://i.imgur.com/j7QlNQ5.png",
        large: "https://i.imgur.com/j7QlNQ5l.png",
        behind: "https://i.imgur.com/12wsHe7h.png",
        resolution: "2400 x 3000",
        size: "1.78",
      },
      {
        title: "HAPPY LOCKER",
        date: "29-Sep-2021",
        url: "https://i.imgur.com/XUDdyT9.png",
        large: "https://i.imgur.com/XUDdyT9l.png",
        behind: "https://i.imgur.com/McTitEYh.png",
        resolution: "2400 x 3000",
        size: "3.48",
      },
      {
        title: "LASER BREATH",
        date: "30-Sep-2021",
        url: "https://i.imgur.com/gfhMWJZ.png",
        large: "https://i.imgur.com/gfhMWJZl.png",
        behind: "https://i.imgur.com/wIF9gp2h.png",
        resolution: "2400 x 3000",
        size: "4.57",
      },
      {
        title: "CRYSTAL SPIDER 🕷️",
        date: "01-Oct-2021",
        url: "https://i.imgur.com/EIZ8rNY.png",
        large: "https://i.imgur.com/EIZ8rNYl.png",
        behind: "https://i.imgur.com/RLrJ0mch.png",
        resolution: "2400 x 3000",
        size: "4.67",
      },
    ],
  },
  {
    number: 15,
    title: "",
    posts: [
      {
        title: "SKULL CRUSHER",
        date: "04-Oct-2021",
        url: "https://i.imgur.com/tpZBBaR.png",
        large: "https://i.imgur.com/tpZBBaRl.png",
        behind: "https://i.imgur.com/coqPUxhh.png",
        resolution: "2400 x 3000",
        size: "3.89",
      },
      {
        title: "RAVEN",
        date: "05-Oct-2021",
        url: "https://i.imgur.com/mKVM1ls.png",
        large: "https://i.imgur.com/mKVM1lsl.png",
        behind: "https://i.imgur.com/xAPQkS4h.png",
        resolution: "2400 x 3000",
        size: "4.44",
      },
      {
        title: "RETRO VIBES",
        date: "06-Oct-2021",
        url: "https://i.imgur.com/EZJP5VL.png",
        large: "https://i.imgur.com/EZJP5VLl.png",
        behind: "https://i.imgur.com/gkqi1CAh.png",
        resolution: "2400 x 3000",
        size: "2.27",
      },
      {
        title: "BASE",
        date: "07-Oct-2021",
        url: "https://i.imgur.com/5jf2gNY.png",
        large: "https://i.imgur.com/5jf2gNYl.png",
        behind: "https://i.imgur.com/RWE97ash.png",
        resolution: "2400 x 3000",
        size: "2.50",
      },
      {
        title: "RING",
        date: "08-Oct-2021",
        url: "https://i.imgur.com/y9KkYI1.png",
        large: "https://i.imgur.com/y9KkYI1l.png",
        behind: "https://i.imgur.com/ACzH7L7h.png",
        resolution: "2400 x 3000",
        size: "4.83",
      },
    ],
  },
];
