export const photoshop = [
  {
    id: 1,
    url: "https://i.imgur.com/aO4z9dxl.png",
    date: "29-Aug-2020",
    description: '"@pame_nyan"',
  },
  {
    id: 2,
    url: "https://i.imgur.com/u9OsQg6l.png",
    date: "03-Sep-2020",
    description: '"IMAGINATION"',
  },
  {
    id: 3,
    url: "https://i.imgur.com/YceModNl.png",
    date: "04-Sep-2020",
    description: '"AppleHead"',
  },
  {
    id: 4,
    url: "https://i.imgur.com/zPx6pEfl.png",
    date: "08-Sep-2020",
    description: '"INNER BEAUTY"',
  },
  {
    id: 5,
    url: "https://i.imgur.com/xs0AtxPl.png",
    date: "20-Dic-2020",
    description: '"ABSURD"',
  },
  {
    id: 6,
    url: "https://i.imgur.com/hZd1uNKl.png",
    date: "10-Jan-2021",
    description: '"ALICE"',
  },
  {
    id: 7,
    url: "https://i.imgur.com/ogHzYe0l.png",
    date: "04-Sep-2020",
    description: '"FACING"',
  },
  {
    id: 8,
    url: "https://i.imgur.com/U3zOBpol.png",
    date: "27-Sep-2020",
    description: '"BLINDED"',
  },
  {
    id: 9,
    url: "https://i.imgur.com/d5YPlTzl.png",
    date: "21-Jan-2021",
    description: '"CHILL"',
  },
  {
    id: 10,
    url: "https://i.imgur.com/QK3CT9Ql.png",
    date: "06-Dic-2020",
    description: '"DEEP DANCE"',
  },
  {
    id: 11,
    url: "https://i.imgur.com/w7HoqGWl.png",
    date: "17-Dic-2020",
    description: '"FLAMINGO"',
  },
  {
    id: 12,
    url: "https://i.imgur.com/WDroRANl.png",
    date: "26-Sep-2020",
    description: '"DUALITY"',
  },
  {
    id: 13,
    url: "https://i.imgur.com/nI0jkzzl.png",
    date: "12-Dic-2020",
    description: '"FLY HIGH"',
  },
  {
    id: 14,
    url: "https://i.imgur.com/I7KkTqdl.png",
    date: "07-Jan-2021",
    description: '"FOXY"',
  },
  {
    id: 15,
    url: "https://i.imgur.com/FQZvj2El.png",
    date: "07-Mar-2021",
    description: '"FRACTURE"',
  },
  {
    id: 16,
    url: "https://i.imgur.com/dnLRWAil.png",
    date: "15-Jan-2021",
    description: '"GOAT ABDUCTION"',
  },
  {
    id: 17,
    url: "https://i.imgur.com/KulkEN0l.png",
    date: "02-Jan-2020",
    description: '"HBD"',
  },
  {
    id: 18,
    url: "https://i.imgur.com/eZHRMnRl.png",
    date: "11-Jan-2021",
    description: '"HOPE"',
  },
  {
    id: 19,
    url: "https://i.imgur.com/kJRpIxLl.png",
    date: "28-Sep-2020",
    description: '"IMPOSTOR"',
  },
  {
    id: 20,
    url: "https://i.imgur.com/VOv8EABl.png",
    date: "09-Dic-2020",
    description: '"THE TOMB OF THE FIREFLIES"',
  },
  {
    id: 21,
    url: "https://i.imgur.com/qgGuloVl.png",
    date: "17-Dic-2020",
    description: '"FLOATING CASTLE"',
  },
  {
    id: 22,
    url: "https://i.imgur.com/VluKWrel.png",
    date: "03-Mar-2021",
    description: '"LIKE A FOOL"',
  },
  {
    id: 23,
    url: "https://i.imgur.com/IyfNkRcl.png",
    date: "25-Feb-2021",
    description: '"MISSUNDERSTOOD"',
  },
  {
    id: 24,
    url: "https://i.imgur.com/6VfOoHRl.png",
    date: "28-Dic-2020",
    description: '"MORPH"',
  },
  {
    id: 25,
    url: "https://i.imgur.com/QhXLXizl.png",
    date: "06-Jan-2021",
    description: '"ON FIRE"',
  },
  {
    id: 26,
    url: "https://i.imgur.com/nKBB0Bxl.png",
    date: "18-Jan-2021",
    description: '"PANIC"',
  },
  {
    id: 27,
    url: "https://i.imgur.com/lv1f1B4l.png",
    date: "29-Dic-2020",
    description: '"POSEIDON"',
  },
  {
    id: 28,
    url: "https://i.imgur.com/3guHuZWl.png",
    date: "13-Jan-2021",
    description: '"PRISMATIC"',
  },
  {
    id: 29,
    url: "https://i.imgur.com/RiMK2PIl.png",
    date: "11-Jan-2021",
    description: '"PURIFY"',
  },
  {
    id: 30,
    url: "https://i.imgur.com/RlbE38Gl.png",
    date: "31-Dic-2020",
    description: '"RABBIT INVASION"',
  },
  {
    id: 31,
    url: "https://i.imgur.com/jbWurJsl.png",
    date: "22-Jan-2021",
    description: '"RADIOACTIVE"',
  },
  {
    id: 32,
    url: "https://i.imgur.com/pXRTsijl.png",
    date: "14-Jan-2021",
    description: '"REBOOT"',
  },
  {
    id: 33,
    url: "https://i.imgur.com/kKiYOYEl.png",
    date: "20-Jan-2021",
    description: '"SKATE MOON"',
  },
  {
    id: 34,
    url: "https://i.imgur.com/bqKb6z6l.png",
    date: "15-Dic-2020",
    description: '"SMITTEN"',
  },
  {
    id: 35,
    url: "https://i.imgur.com/lHaj7bIl.png",
    date: "27-Dic-2020",
    description: '"TIME FLIES"',
  },
  {
    id: 36,
    url: "https://i.imgur.com/2TX5LSul.png",
    date: "25-Feb-2021",
    description: '"SPACE-REX"',
  },
];
